<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Seeder;

class StudentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * This seeder populates student data from Excel.
     * When a punch comes in with a roll number that matches seeded data,
     * the student details (name, father's name, class, batch) will automatically appear.
     * 
     * If a punch comes in for a roll number NOT in this seeder,
     * it will show only the roll number with an option to edit.
     */
    public function run(): void
    {
        // Student data array - Extracted from Excel file
        $students = [
            [
                'roll_number' => '25175000001',
                'name' => 'MAYANK KUMAR',
                'father_name' => 'MAHENDER KUMAR',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000007',
                'name' => 'SAMYAK GAUTAM',
                'father_name' => 'CHANDRESH GAUTAM',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000008',
                'name' => 'MOHIT JAIN',
                'father_name' => 'SONU JAIN',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000009',
                'name' => 'VAISHNAVI BANSAL',
                'father_name' => 'ANURAG BANSAL',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000010',
                'name' => 'HIMANK CHAUDHARY',
                'father_name' => 'SAURABH CHAUDHARY',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000011',
                'name' => 'KUSHAGRA KHANDELWAL',
                'father_name' => 'ANUJ KHANDELWAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000012',
                'name' => 'NAINA GOYAL',
                'father_name' => 'RADHEY SHYAM GOYAL',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000013',
                'name' => 'DHRUV KUMAR',
                'father_name' => 'DIGAMVAR SINGH',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000014',
                'name' => 'TANVI SONI',
                'father_name' => 'VINOD KUMAR',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000015',
                'name' => 'VISHESH SHARMA',
                'father_name' => 'RAMAN KUMAR',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000016',
                'name' => 'SHAURYA SRIVASTAVA',
                'father_name' => 'MOHIT SRIVASTAVA',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000017',
                'name' => 'YASHI SAGAR',
                'father_name' => 'RANJEET KUMAR',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000018',
                'name' => 'YASHITA AGARWAL',
                'father_name' => 'SANDEEP',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000019',
                'name' => 'PRATEEK SHARMA',
                'father_name' => 'HARIOM SHARMA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000020',
                'name' => 'UTKARSH YADAV',
                'father_name' => 'RAVENDRA SINGH',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000021',
                'name' => 'HARDIK RAJPUT',
                'father_name' => 'LAVENDRA KUMAR',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000022',
                'name' => 'PARINATI JAIN',
                'father_name' => 'MANISH JAIN',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000023',
                'name' => 'TEJASAV VASHISHTHA',
                'father_name' => 'BHUPENDRA MOHAN SHARMA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000024',
                'name' => 'ASMITA RAJ',
                'father_name' => 'AMIT RAJ',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000025',
                'name' => 'DEV UPADHYAY',
                'father_name' => 'MANISH UPADHAYA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000026',
                'name' => 'SURYANSH SINGH',
                'father_name' => 'ATUL KUMAR',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000027',
                'name' => 'KRISHNA GUPTA',
                'father_name' => 'RAJKUMAR GUPTA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000028',
                'name' => 'ADITYA AGARWAL',
                'father_name' => 'SANDEEP GARG',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000029',
                'name' => 'ADITYA AGARWAL',
                'father_name' => 'PANKAJ AGARWAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000030',
                'name' => 'PAYAL JAIN',
                'father_name' => 'AMIT JAIN',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000031',
                'name' => 'SHLOK',
                'father_name' => 'RAVI KUMAR GARG',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000032',
                'name' => 'NAITIK',
                'father_name' => 'RAVI KUMAR',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000033',
                'name' => 'ANANT AGARWAL',
                'father_name' => 'SACHIN AGARWAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000034',
                'name' => 'LOVE GUPTA',
                'father_name' => 'RAJESH GUPTA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000035',
                'name' => 'PRASHANT TOMAR',
                'father_name' => 'VIJAY SINGH TOMAR',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000036',
                'name' => 'ADITYA JAIN',
                'father_name' => 'AJAY KUMAR JAIN',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000037',
                'name' => 'SHIVA GUPTA',
                'father_name' => 'RAJEEV GUPTA',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000038',
                'name' => 'VIDWAN GUPTA',
                'father_name' => 'ATUL GUPTA',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000039',
                'name' => 'SHAURYA UPADHYAY',
                'father_name' => 'DEEPESH UPADHYAY',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000040',
                'name' => 'MANTEJ SINGH',
                'father_name' => 'TARANPREET SINGH',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000041',
                'name' => 'PRASHANT KUMAR SINGH',
                'father_name' => 'MANOJ KUMAR',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000042',
                'name' => 'RIYA SINGH',
                'father_name' => 'MESHPAL SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000043',
                'name' => 'ARADHYA GOYAL',
                'father_name' => 'AKHIL GOYAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000044',
                'name' => 'VANSH GOYAL',
                'father_name' => 'SUNIL GOYAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000045',
                'name' => 'RISHIT SINGHAL',
                'father_name' => 'VISHAL SINGHAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000046',
                'name' => 'HARSHIKA SENGAR',
                'father_name' => 'AMAR SINGH SENGAR',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000047',
                'name' => 'UTKARSH',
                'father_name' => 'JOGENDRA SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000048',
                'name' => 'ANUBHAV SINGHAL',
                'father_name' => 'KAMTA NATH SINGHAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000049',
                'name' => 'DEVANSH JUREL',
                'father_name' => 'SANDEEP KUMAR',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000050',
                'name' => 'DIVYANSHU UPADHAYA',
                'father_name' => 'DHEERENDRA KR. UPADHAYA',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000051',
                'name' => 'AYUSH SHARMA',
                'father_name' => 'RAHUL SHARMA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000052',
                'name' => 'PRAKHAR BHARDWAJ',
                'father_name' => 'SANDEEP KUMAR BHARDWAJ',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000053',
                'name' => 'TANISHQ JAIN',
                'father_name' => 'GAURAV JAIN',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000054',
                'name' => 'ALIMA',
                'father_name' => 'PARVESH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000055',
                'name' => 'AMRITANSH MISHRA',
                'father_name' => 'HARSH NARAYAN MISHRA',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000056',
                'name' => 'YUVAAN GAUTAM',
                'father_name' => 'MANISH KUMAR',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000057',
                'name' => 'GAURANSH SINGHAL',
                'father_name' => 'MANISH KUMAR SINGHAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000058',
                'name' => 'SKAND SHARMA',
                'father_name' => 'MANISH SHARMA',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000059',
                'name' => 'SHLOK SHARMA',
                'father_name' => 'MANISH SHARMA',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000060',
                'name' => 'TANUJ SINGH',
                'father_name' => 'RAGHUNATH SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000061',
                'name' => 'NIKHIL KUMAR SUTEL',
                'father_name' => 'SHIVAM KUMAR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000062',
                'name' => 'ARYAN JAIN',
                'father_name' => 'PAWAN JAIN',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000063',
                'name' => 'ISHANT SINGHAL',
                'father_name' => 'PRADEEP SINGHAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000064',
                'name' => 'SAMARTH KULSHRESHTHA',
                'father_name' => 'MANISH KULSHRESTHA',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000065',
                'name' => 'RASHMI',
                'father_name' => 'LALSINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000066',
                'name' => 'RITIK KUMAR',
                'father_name' => 'DHARAMVIR SINGH',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000067',
                'name' => 'SOMYA DIXIT',
                'father_name' => 'NAVEEN DIXIT',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000068',
                'name' => 'VANSH SINGH',
                'father_name' => 'PRADEEP SINGH',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000069',
                'name' => 'ASTHA BANSAL',
                'father_name' => 'DEEPAK BANSAL',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000070',
                'name' => 'VIVEK SINGH',
                'father_name' => 'KRISHNA VEER SINGH',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000071',
                'name' => 'ARNIKA AGARWAL',
                'father_name' => 'RAKESH KUMAR',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000072',
                'name' => 'VISHNU KANT',
                'father_name' => 'HODIL SINGH',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000073',
                'name' => 'YATI GUPTA',
                'father_name' => 'VISHAL GUPTA',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000074',
                'name' => 'MOHIT RATHORE',
                'father_name' => 'RAJKUMAR RATHORE',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000075',
                'name' => 'TANVI KUSHWAHA',
                'father_name' => 'SATYPRAKASH KUSHWAHA',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000076',
                'name' => 'VIGHNESH GUPTA',
                'father_name' => 'RAJESH KUMAR GUPTA',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000077',
                'name' => 'TEENA VERMA',
                'father_name' => 'SANJEEV VERMA',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000078',
                'name' => 'JATIN KUMAR JHA',
                'father_name' => 'KAUSHAL SINGH',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000079',
                'name' => 'DEV KUMAR RAWAT',
                'father_name' => 'AVDESH KUMAR',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000080',
                'name' => 'DIVANSHU BHARDWAJ',
                'father_name' => 'VED PRAKASH',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000174',
                'name' => 'MITALI MITTAL',
                'father_name' => 'SUNIL MITTAL',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000175',
                'name' => 'MANTSHA USMANI',
                'father_name' => 'KURBAAN USMANI',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000176',
                'name' => 'AGAM YADAV',
                'father_name' => 'HARENDRA SINGH',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000177',
                'name' => 'HARMIT MAHAJAN',
                'father_name' => 'RAVINDER MAHAJAN',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000178',
                'name' => 'AMAN YADAV',
                'father_name' => 'NARENDRA SINGH YADAV',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000179',
                'name' => 'MANYA SHARMA',
                'father_name' => 'SAURABH SHARMA',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000180',
                'name' => 'DIVANSHU BHARDWAJ',
                'father_name' => 'VED PRAKASH',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000181',
                'name' => 'RUDRA GUPTA',
                'father_name' => 'DEEPAK GUPTA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000182',
                'name' => 'ARYAN SINGH PAL',
                'father_name' => 'ASHUTOSH KUMAR',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000183',
                'name' => 'GAYATRI UV SINGH',
                'father_name' => 'VINEET SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000184',
                'name' => 'JAYVEER SINGH',
                'father_name' => 'HARIOM',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000185',
                'name' => 'VARUN BHARWANI',
                'father_name' => 'MAHESH BHARWANI',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000186',
                'name' => 'PRARABDH PRAJAPATI',
                'father_name' => 'SATYEN KUMAR PRAJAPATI',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000187',
                'name' => 'DIVYANSH SINGH',
                'father_name' => 'SUNEEL SINGH',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000188',
                'name' => 'ARIHANT JAIN',
                'father_name' => 'RAJESH JAIN',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000189',
                'name' => 'EKANSH GARG',
                'father_name' => 'SUMITAGARWAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000190',
                'name' => 'ABHINAV UPADHYAY',
                'father_name' => 'SANJEEV UPADHYAY',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000191',
                'name' => 'SHUBHAM SHARMA',
                'father_name' => 'NAVEEN SHARMA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000192',
                'name' => 'SANKALP JAIN',
                'father_name' => 'DEEPANSHU JAIN',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000193',
                'name' => 'TANMAY AGARWAL',
                'father_name' => 'KRISHNA KUMAR AGARWAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000194',
                'name' => 'SHREYAS GUPTA',
                'father_name' => 'OMKANT GUPTA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000195',
                'name' => 'VYOM GUPTA',
                'father_name' => 'PANKAJ GUPTA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000196',
                'name' => 'ARPIT GUPTA',
                'father_name' => 'RATNESH GUPTA',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000197',
                'name' => 'AARAV BINDAL',
                'father_name' => 'OMPRAKASH BINDAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000198',
                'name' => 'PRATHAM SHARMA',
                'father_name' => 'VISHAL SHARMA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000199',
                'name' => 'DEVANSHU KUMAR',
                'father_name' => 'DILIP KUMAR',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000200',
                'name' => 'MUDIT AGARWAL',
                'father_name' => 'ANAND AGARWAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000201',
                'name' => 'VEDANT',
                'father_name' => 'SANJAY KUMAR',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000202',
                'name' => 'SHREYANSH AGARWAL',
                'father_name' => 'AMIT AGARWAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000203',
                'name' => 'LAVI SHARMA',
                'father_name' => 'PANKAJ SHARMA',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000204',
                'name' => 'AAYUSH YADAV',
                'father_name' => 'MANOJ KUMAR YADAV',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000205',
                'name' => 'VINAYAK SOME',
                'father_name' => 'ANURAG SOME',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000212',
                'name' => 'VIVEK JADON',
                'father_name' => 'JAYPAL SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000213',
                'name' => 'MOHIT',
                'father_name' => 'SARBESH SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000214',
                'name' => 'AYUSH GUPTA',
                'father_name' => 'RAMNARYAN GUPTA',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000215',
                'name' => 'ARPIT SHARMA',
                'father_name' => 'MR. ACHAL SHARMA',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000216',
                'name' => 'SHAURYA FARSAIYA',
                'father_name' => 'SUARABH GUPTA',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000217',
                'name' => 'ARCHIT JAIN',
                'father_name' => 'VISHAL JAIN',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000218',
                'name' => 'ANSHU PARASAR',
                'father_name' => 'MANOJ PARASAR',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000219',
                'name' => 'ABHISHEK GURJAR',
                'father_name' => 'DEVENDRA SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000220',
                'name' => 'ATHARV KAUSHIK',
                'father_name' => 'PANKAJ KAUSHIK',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000221',
                'name' => 'PAYAL TOMAR',
                'father_name' => 'BRJMOHAN TOMAR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000230',
                'name' => 'ADITYA SINGH',
                'father_name' => 'RAM SINGH',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000243',
                'name' => 'NAITIK SHARMA',
                'father_name' => 'PRAVEEN SHARMA',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000244',
                'name' => 'ABIKA AGARWAL',
                'father_name' => 'RITU AGARWAL',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000245',
                'name' => 'SANSKRITI RATHORE',
                'father_name' => 'MANISH RATHORE',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000247',
                'name' => 'VEDANSH GUPTA',
                'father_name' => 'SUNIL GUPTA',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000291',
                'name' => 'SACHIN CHAUHAN',
                'father_name' => 'CHANDRA SHEKHAR CHAUHAN',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000292',
                'name' => 'SHIVAM TOMAR',
                'father_name' => 'HARENDRA PAL',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000295',
                'name' => 'BHUMI JADON',
                'father_name' => 'BHURI SINGH',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000296',
                'name' => 'NARESH JADON',
                'father_name' => 'DIMAN SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000297',
                'name' => 'PRIYANSHI YADAV',
                'father_name' => 'SANJEEV YADAV',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000300',
                'name' => 'MAYRA HUSSAIN',
                'father_name' => 'SHAHID HUSSAIN',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000301',
                'name' => 'SAKSHI MUDGAL',
                'father_name' => 'SUBHASH CHAND SHARMA',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000302',
                'name' => 'BHARAT KUMAR',
                'father_name' => 'RAMSEVAK',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000306',
                'name' => 'PRATHAM SHARMA',
                'father_name' => 'BHUPENDRA SHARMA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000307',
                'name' => 'SAKHI GOYAL',
                'father_name' => 'SUMIT GOYAL',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000309',
                'name' => 'SHUBH SHARMA',
                'father_name' => 'KRISHNA KANT SHARMA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000310',
                'name' => 'ANNU KUSHWAHA',
                'father_name' => 'MUKESH BABU',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000311',
                'name' => 'GAURAV',
                'father_name' => 'SATISH KUMAR',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000312',
                'name' => 'JATIN KUMAR',
                'father_name' => 'SANJAY KUMAR',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000313',
                'name' => 'MOHD AMEER HAMZA',
                'father_name' => 'MOHD IMRAAN',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000314',
                'name' => 'DEVANSH DHAKED',
                'father_name' => 'BHAGWAN SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000315',
                'name' => 'PRINCE',
                'father_name' => 'PRAVESH KUMAR',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000316',
                'name' => 'TANISHQ UPADHAYA',
                'father_name' => 'LATE RAKESH UPADHYAY',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000317',
                'name' => 'ANURAG SINGH',
                'father_name' => 'LOKENDRA SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000318',
                'name' => 'DEEKSHA SINGH',
                'father_name' => 'DHARMVIR SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000319',
                'name' => 'PRASHANT',
                'father_name' => 'RADHARAMAN',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000320',
                'name' => 'ANEKDEEP',
                'father_name' => 'PRAGYAVEER',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000321',
                'name' => 'AJAY GURJAR',
                'father_name' => 'NARENDRA SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000322',
                'name' => 'SHIVAM DHAKREY',
                'father_name' => 'PUSHPENDRA SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000323',
                'name' => 'ANKUSH KUMAR',
                'father_name' => 'RAM LAKHAN',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000324',
                'name' => 'PANKAJ SINGH',
                'father_name' => 'GOPI CHAND',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000325',
                'name' => 'KAJAL',
                'father_name' => 'AJAY KUMAR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000326',
                'name' => 'NITIN',
                'father_name' => 'SONVIR SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000327',
                'name' => 'ATUL KUMAR',
                'father_name' => 'MUKESH KUMAR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000328',
                'name' => 'VIVEK YADAV',
                'father_name' => 'BRIJESH KUMAR YADAV',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000329',
                'name' => 'DEVESH',
                'father_name' => 'ANIL KUMAR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000330',
                'name' => 'MUSKAN KUSHWAHA',
                'father_name' => 'RAKESH KUMAR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000331',
                'name' => 'SHIVAM SHARMA',
                'father_name' => 'DAYA SHANKAR SHARMA',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000332',
                'name' => 'SHIVAM UPADHAYA',
                'father_name' => 'CHANDRABHAN',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000333',
                'name' => 'MOHIT PRAJAPATI',
                'father_name' => 'BANTI',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000334',
                'name' => 'PRADHYUN CHAHAR',
                'father_name' => 'YASHPAL SINGH CHAHAR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000335',
                'name' => 'ARYAN SHARMA',
                'father_name' => 'AMIT KUMAR SHARMA',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000336',
                'name' => 'NISHANT RAJPUT',
                'father_name' => 'DILEEP',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000337',
                'name' => 'NITIN TYAGI',
                'father_name' => 'SATYENDRA KUMAR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000338',
                'name' => 'VIDYUT KUMBHARE',
                'father_name' => 'GHANSHYAM KUMBHARE',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000339',
                'name' => 'ABHISHEK',
                'father_name' => 'SIYARAM SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000340',
                'name' => 'BHASKAR LAWANIYA',
                'father_name' => 'NARENDRA KUMAR SHARMA',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000341',
                'name' => 'RAJKUMAR',
                'father_name' => 'JAYVIR SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000342',
                'name' => 'SHIVANSH',
                'father_name' => 'MAN SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000343',
                'name' => 'SIDDHARTH',
                'father_name' => 'YOGANDRA SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000344',
                'name' => 'SHALINI',
                'father_name' => 'RAJESH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000345',
                'name' => 'RANJNA',
                'father_name' => 'BHOORI SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000346',
                'name' => 'NARENDRA',
                'father_name' => 'YOGENDRA SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000347',
                'name' => 'KHUSHI DUBEY',
                'father_name' => 'BANWARI LAL DUBEY',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000348',
                'name' => 'MAHI SIKARWAR',
                'father_name' => 'RAM BARAN',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000349',
                'name' => 'HARSH',
                'father_name' => 'RAVINDRA KUMAR',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000350',
                'name' => 'GUNGUN',
                'father_name' => 'SUJAN SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000351',
                'name' => 'DIVYANSHI',
                'father_name' => 'RAJPAL TYAGI',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000352',
                'name' => 'DEEKSHA SHARMA',
                'father_name' => 'RAJIV KUMAR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000353',
                'name' => 'ARYAN PIPESH',
                'father_name' => 'MANOJ KUMAR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000354',
                'name' => 'ANKITA',
                'father_name' => 'NEPAL SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000355',
                'name' => 'ROOPAL',
                'father_name' => 'AJAY KUMAR',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000356',
                'name' => 'HEMANT GAUTAM',
                'father_name' => 'ATUL KUMAR GAUTAM',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000357',
                'name' => 'NRAPENDRA PRATAP SINGH',
                'father_name' => 'BHANU PRATAP SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000358',
                'name' => 'RAUNAK AGARWAL',
                'father_name' => 'PAWAN AGARWAL',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000359',
                'name' => 'YUKTI SHARMA',
                'father_name' => 'SUMIT KUMAR SHARMA',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000360',
                'name' => 'ARYAN DIXIT',
                'father_name' => 'JAGMOHAN',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000365',
                'name' => 'ANKIT KUMAR',
                'father_name' => 'VIMAL KUMAR',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000366',
                'name' => 'PARAS YADAV',
                'father_name' => 'SUBHASH CHANDRA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000367',
                'name' => 'SAKSHAM RAJPUT',
                'father_name' => 'VIKRAM RAJPUT',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000368',
                'name' => 'RAUNAK GHOSH',
                'father_name' => 'LAKSHNAM CHANDRA GHOSH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000369',
                'name' => 'LAKSHYA SINGH',
                'father_name' => 'AMIT KUMAR SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000370',
                'name' => 'SARTHAK MANGAL',
                'father_name' => 'SUBHASH MANGAL',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000371',
                'name' => 'AYUSHI RAJPUT',
                'father_name' => 'VIJAY SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000372',
                'name' => 'JUBAIR',
                'father_name' => 'CHAMAN ALI',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000377',
                'name' => 'GAGANJEET SINGH',
                'father_name' => 'HARIOM SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000382',
                'name' => 'ADARSH AGARWAL',
                'father_name' => 'MANOJ AGARWAL',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000388',
                'name' => 'KHUSHI SINGH',
                'father_name' => 'KHETRA PAL SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000402',
                'name' => 'YUKTI GAUTAM',
                'father_name' => 'AVDESH KUMAR',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000403',
                'name' => 'ABHAY GAUTAM',
                'father_name' => 'SUSHIL KUMAR GAUTAM',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000404',
                'name' => 'YUVRAJ SONI',
                'father_name' => 'PRAMENDRA SONI',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000405',
                'name' => 'AARAV CHAUDHARY',
                'father_name' => 'AMIT CHAUDHARY',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000406',
                'name' => 'NIYATI AGARWAL',
                'father_name' => 'MR. NISHANT AGARWAL',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000407',
                'name' => 'DEVESH CHAUDHARY',
                'father_name' => 'SHRINIVASH SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000408',
                'name' => 'ABHINAV RAJPUT',
                'father_name' => 'SHER SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000409',
                'name' => 'JATIN SIKARWAR',
                'father_name' => 'RUPENDRA SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000411',
                'name' => 'ABHINAV JACOB',
                'father_name' => 'HEROLO JACOB',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000413',
                'name' => 'SUGAM YADAV',
                'father_name' => 'ABANESH KUMAR YADAV',
                'class_course' => '11',
                'batch' => '25H1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000415',
                'name' => 'ASHI SHARMA',
                'father_name' => 'YOGESH KUMAR SHARMA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000416',
                'name' => 'AVANTIKA',
                'father_name' => 'JANKI PRASAD',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000417',
                'name' => 'ISHIKA PARIHAR',
                'father_name' => 'NAND KISHOR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000418',
                'name' => 'JATIN',
                'father_name' => 'AJAYPAL SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000419',
                'name' => 'MOHD JEESHAN QURESHI',
                'father_name' => 'ABDUL MUEEN QURESHI',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000420',
                'name' => 'PRAVEEN',
                'father_name' => 'NAHAR SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000421',
                'name' => 'SHIVANI TOMAR',
                'father_name' => 'DESHRAJ TOMAR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000422',
                'name' => 'LAVI KUMARI',
                'father_name' => 'BIRENDRA SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000427',
                'name' => 'JATIN GOSWAMI',
                'father_name' => 'KRISHNA GIRI',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000429',
                'name' => 'PRIYANSHU',
                'father_name' => 'LAXMI NARAYAN',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000430',
                'name' => 'ARYAN',
                'father_name' => 'RAJU',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000431',
                'name' => 'NARESH KUMAR',
                'father_name' => 'MAHESH CHANDRA CHAHAR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000432',
                'name' => 'TANVI RAJPUT',
                'father_name' => 'MANOJ KUMAR',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000433',
                'name' => 'HARSH RAJ',
                'father_name' => 'SANJAY KUMAR',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000434',
                'name' => 'ARUSH SHARMA',
                'father_name' => 'ARVIND KUMAR',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000442',
                'name' => 'SUSHANT PRATAP INDOLIYA',
                'father_name' => 'KHUSHHAL SINGH',
                'class_course' => '11',
                'batch' => '25P3AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000443',
                'name' => 'ATHARV GUPTA',
                'father_name' => 'S.K GUPTA',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000444',
                'name' => 'PAWAN KUMAR',
                'father_name' => 'ANIL KUMAR',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000445',
                'name' => 'LUCKY',
                'father_name' => 'HARENDRA SINGH',
                'class_course' => '11',
                'batch' => '25P1AG',
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000449',
                'name' => 'ABHISHEK SHARMA',
                'father_name' => 'PRAMENDRA SHARMA',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000450',
                'name' => 'MUSKAN CHAUHAN',
                'father_name' => 'SANJAY SINGH',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000451',
                'name' => 'MOHAN PRATAP',
                'father_name' => 'VISHNU KUMR GUPTA',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000466',
                'name' => 'TANYA SINGH',
                'father_name' => 'MANOJ KUMAR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000468',
                'name' => 'MEGHA SHARMA',
                'father_name' => 'PANKAJ SHARMA',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
            [
                'roll_number' => '25175000469',
                'name' => 'SOMYA',
                'father_name' => 'ADARSH KUMAR',
                'class_course' => '11',
                'batch' => null,
                'parent_phone' => null,
                'alerts_enabled' => true,
            ],
        ];

        $created = 0;
        $updated = 0;

        foreach ($students as $studentData) {
            $student = Student::firstOrCreate(
                ['roll_number' => $studentData['roll_number']],
                $studentData
            );

            if ($student->wasRecentlyCreated) {
                $created++;
                $this->command->info("Created: {$studentData['roll_number']} - {$studentData['name']}");
            } else {
                // Update existing record only if it has no data (preserve existing data)
                $needsUpdate = false;
                $updateData = [];
                
                if (empty($student->name) && !empty($studentData['name'])) {
                    $updateData['name'] = $studentData['name'];
                    $needsUpdate = true;
                }
                if (empty($student->father_name) && !empty($studentData['father_name'])) {
                    $updateData['father_name'] = $studentData['father_name'];
                    $needsUpdate = true;
                }
                if (empty($student->class_course) && !empty($studentData['class_course'])) {
                    $updateData['class_course'] = $studentData['class_course'];
                    $needsUpdate = true;
                }
                if (empty($student->batch) && !empty($studentData['batch'])) {
                    $updateData['batch'] = $studentData['batch'];
                    $needsUpdate = true;
                }
                if (empty($student->parent_phone) && !empty($studentData['parent_phone'])) {
                    $updateData['parent_phone'] = $studentData['parent_phone'];
                    $needsUpdate = true;
                }
                
                if ($needsUpdate) {
                    $student->update($updateData);
                    $updated++;
                    $this->command->info("Updated: {$studentData['roll_number']} - {$studentData['name']}");
                }
            }
        }

        $this->command->info("\nSeeder complete!");
        $this->command->info("Created: {$created} new student records");
        $this->command->info("Updated: {$updated} existing student records");
        $this->command->info("Total students now: " . Student::count());
    }
}
